version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run: echo 'installing packages'
      - run: npm install
      - run: CI=true npm run build
  test: 
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run: echo 'testing'
      - run: npm install
      - run: npm test
  this_is_a_dependency:
    docker:
      - image: circleci/node:14.5.0
    steps:
      - checkout
      - run: echo 'you shall pass'
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - test:
          requires:
            - this_is_a_dependency
